### ISSUE TITLE
peaks displayed too low

### ISSUE THREAD

**Issue by tdhock** [PeakLearner/PeakLearner#75]
mean values seem to be too low / incorrect in several tracks.
![image](https://user-images.githubusercontent.com/932850/129801402-5e05244d-0b1f-4d0e-9eab-4c7fdf3bf55a.png)
@deltarod can you please investigate/ fix?

**Comment by tdhock** [comment]
another example, this is pretty strange. what's going on?
![image](https://user-images.githubusercontent.com/932850/129932524-c9bb9ebc-e5f3-407a-9c3d-b9e6b5e383fc.png)

**Comment by tdhock** [comment]
sometimes too high also,
![image](https://user-images.githubusercontent.com/932850/129935803-18003bd3-ed49-49a5-a8d2-5605ac9f9cae.png)

**Comment by tdhock** [comment]
@deltarod any idea what the problem is or how to fix? this is really strange from a user interface / data visualization perspective.

**Comment by deltarod** [comment]
Not sure yet, I haven't looked into it.

**Comment by tdhock** [comment]
this is still an issue

**Comment by deltarod** [comment]
Height is being calculated by taking the mean from FLOPART and dividing it by lenBin, which is the number of datapoints in each summarized data point. The length of the bin is calculated by finding the difference between the end/start of the query and dividing it by the total number of bins. The total number of bins is taken by multiplying the end/start difference by the scale. The total number of bins should also be the amount of pixels which the user can see in the genome view.

This issue seems to be either something FLOPART is doing with the mean, or the input data itself being wrong. 

I could try and recalculate the mean using the datapoints and the start/end values of the peak?

**Comment by tdhock** [comment]
FLOPART should return correct means (for given input data values). I am using it for these figures https://github.com/tdhock/LabeledFPOP-paper#13-sept-2021 and it works fine.
What are the input data values you are using? maybe there is some numerical issue with rounding to integer?
